---
version: 2
references:
  workspace_root: &workspace_root
    /tmp/workspace

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

job-defaults: &job-defaults
  environment:
    - AWS_DEFAULT_REGION: us-west-2
    - AWS_ACCOUNT_ID: "883127560329"
    - VGS_DEV_ARTIFACT_BUCKET: vault-dev-01-audits-01-artifact-19k6160zpr44j
    - AWS_PROFILE: vgs-dev

jobs:
  build:
    working_directory: ~/nginx-ssl-router
    docker:
      - image: circleci/python:3.6
    <<: *job-defaults
    steps:
      - checkout
      - *attach_workspace
      - run:
          name: Setup AWS
          command: ./scripts/env.sh
      - run:
          name: "Python install"
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: "Run ansible"
          command: |
            . venv/bin/activate
            ansible-playbook -i inventory -c local provision-certificates.yml
      - run:
          name: "Build docker"
          command: |
            docker build .
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
