---
# tasks file for nginx-ssl-router

- name: add nginx/stable repo
  apt_repository:
    repo: 'ppa:nginx/stable'

- name: update apt cache
  apt: update_cache=yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: apt install nginx
  apt: name=nginx state=present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Gather facts
  action: ec2_facts

- name: lookup certificates
  shell: "aws s3 ls --recursive s3://{{ ssl_router_s3_bucket }}/{{ ssl_router_s3_path }} | awk '{print $4}'"
  register: s3_keys

- debug: msg="{{ item }}"
  with_items: "{{ s3_keys.stdout_lines  }}"

- name: ensure {{ ssl_router_nginx_config_dir }} exists
  file: path={{ ssl_router_nginx_config_dir }} state=directory

- name: ensure {{ ssl_router_nginx_enabled_dir }} exists
  file: path={{ ssl_router_nginx_enabled_dir }} state=directory

# s3 module failing, using shell command
- name: copy ssl certificates
  shell: aws s3 cp s3://{{ ssl_router_s3_bucket }}/{{ item }} {{ ssl_router_nginx_config_dir }}{{ item | basename }}.cert
  with_items: "{{ s3_keys.stdout_lines }}"

- name: set permissions
  file: path="{{ ssl_router_nginx_config_dir }}{{ item | basename }}.cert" mode=0400
  with_items: "{{ s3_keys.stdout_lines }}"

- name: add nginx.conf
  template: src=templates/nginx.conf.j2 dest=/etc/nginx/nginx.conf mode=0644

- name: add catch all
  template: src=templates/verygoodproxy.conf.j2 dest={{ ssl_router_nginx_config_dir }}verygoodproxy.conf mode=0400

- name: lookup catch all certificate
  shell: "aws s3 ls --recursive s3://{{ ssl_router_s3_bucket }}/ssl.verygoodproxy.cert | awk '{print $4}'"
  register: s3_catch_all_key

- name: add catch all certificate
  shell: aws s3 cp s3://{{ ssl_router_s3_bucket }}/{{ item }} {{ ssl_router_nginx_config_dir }}verygoodproxy.cert
  with_items: "{{ s3_catch_all_key.stdout_lines }}"

- name: activate catch all
  file: src={{ ssl_router_nginx_config_dir }}verygoodproxy.conf dest={{ ssl_router_nginx_enabled_dir }}verygoodproxy.conf state=link force=yes

- name: add tenant configs
  template: src=templates/vault_tenant.conf.j2 dest={{ ssl_router_nginx_config_dir }}{{ item | basename }}.config mode=0400
  with_items: "{{ s3_keys.stdout_lines  }}"
  when: item.startswith('ssl/2/') | bool

- name: create symlink
  file: src={{ ssl_router_nginx_config_dir }}{{ item | basename }}.config dest={{ ssl_router_nginx_enabled_dir }}{{ item | basename }}.config state=link
  with_items: "{{ s3_keys.stdout_lines  }}"
  when: item.startswith('ssl/2/') | bool

- name: delete nginx default config
  file: path=/etc/nginx/conf.d/default.conf state=absent

- name: delete default sites-enabled/default config
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: reload nginx config
  service: name=nginx state=reloaded
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
