# === COMMON TEMPLATES ===
job-defaults: &job-defaults
  working_directory: &working_directory
    ~/nginx-ssl-router

# === JOBS ===
version: 2
jobs:
  build_and_test:
    <<: *job-defaults
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Install Requirements
          command: |
            python -m virtualenv venv
            . venv/bin/activate

            pip install 'ansible>=2.1,<2.2'
            pip install 'boto==2.38.0'
            pip install setuptools --upgrade
            pip install netaddr
      - run:
          name: Test
          command: |
            . venv/bin/activate
            ansible-playbook -i tests/inventory -c local tests/test.yml --syntax-check
            ansible-playbook -i tests/inventory -c local tests/test.yml

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test